plannigan/columbo

- .github/workflows/main.yml
- README.md
- docker-compose.yaml
- docs/CHANGELOG.md
- docs/api.md
- docs/getting-started.md
- docs/index.md
- docs/usage-guide.md
- mkdocs.yml
Includes a starting point for documentation of the project.
I played around with trying to achieve a `_dev/` sub directory to host the rendered docs for a PR, but the page does not load properly. Dynamically creating a `mkdocs.yml` file with the updated `site_url` might work, but it might be an issue with the theme.
For now, the docs are built and uploaded as an artifact.
> Add documentation site

- columbo/_exception.py
- columbo/_interaction.py
- docker/devbox.dockerfile
- docs/api.md
- docs/css/mkdocstrings.css
- mkdocs.yml
- requirements-test.txt
- util/mkdocstrings_patch_type_aliases/mkdocstrings_patch_type_aliases/__init__.py
- util/mkdocstrings_patch_type_aliases/mkdocstrings_patch_type_aliases/_plugin.py
- util/mkdocstrings_patch_type_aliases/setup.py
Includes custom mkdocs plugin to display type aliases (See pawamoy/pytkdocs#80)
> Add API documentation

- .github/actions/publish-docs-with-mike/action.sh
- .github/actions/publish-docs-with-mike/action.yml
- .github/actions/publish-docs-with-mike/configure_git_user.sh
- .github/actions/publish-docs-with-mike/update_docs_for_version.sh
- .github/workflows/main.yml
Merges to the default branch publishes docs to "dev" version.
A follow up PR will use the functionality to create a new numbered version when the version number changes.
Part of #38
> CI action to publish docs to dev version

- README.md
Fixes #78 and fixes #79.
You can see the updated readme [here](https://github.com/wayfair-incubator/columbo/tree/fix-doc-links-78-79).
> Updating/fixing documentation links in README.md

- columbo/__init__.py
- columbo/_cli.py
- columbo/_interaction.py
- columbo/_types.py
- docs/api.md
- docs/usage-guide/validators.md
- requirements.txt
- setup.cfg
- tests/cli_test.py
- tests/interaction_test.py
> Updating validation signature

- columbo/_interaction.py
- docs/usage-guide/validators.md
- mkdocs.yml
- tests/cli_test.py
- tests/interaction_test.py
In this PR, I have:
- Updated _interaction.py to provide a `DeprecationWarning` when a validator using the old paradigm is used
- I chose a `DeprecationWarning` because `DeprecationWarning`s are for "warnings about deprecated features when those warnings are intended for other Python developers" (see https://docs.python.org/3/library/warnings.html#warning-categories) which is the use-case we are going for (from my understanding - but feel free to correct me if I'm wrong on this)
- Updated validator documentation to note:
- That validators using the old paradigm are still supported (although deprecated)
- How to upgrade validator from old paradigm to the new one
- Updated tests to make sure DeprecationWarning is shown
> Adding deprecation warning when old validator signature is used

- setup.cfg
The quotes were being retained in the wheel metadata and resulted in invalid classifiers.
> Remove quotes from package classifiers

- docker/bump_version.sh
The `bump_version.sh` script was previously using `--show-current`, which is not supported in the version of git available on the devbox image (added in git `2.22`, but the debian image is still using `2.20.1`)
> Update command to fetch current branch

- docker/bump_version.sh
Fixes #95
I've tested this locally and it allows the `docker-compose run --rm bump minor` command to run properly.
Thanks to https://salferrarello.com/git-switch/ for the solution.
> Fixing references to git switch

- CHANGELOG.md
- columbo/_interaction.py
- columbo/_types.py
- docs/usage-guide/validators.md
- tests/cli_test.py
- tests/interaction_test.py
- Removed the legacy validator signature
- Updated the tests to account for this
- Updated the docs
- Update the change log
closes #40
> Removing deprecated validator signature

- mkdocs.yml
The plugin is enabled by default. However, if you add a different plugin, the search plugin needs to be explicitly listed.
Fixes #134
> Add search plugin to docs

- docs/usage-guide/interactions.md
I updated the docs for the [Confirm](https://wayfair-incubator.github.io/columbo/latest/usage-guide/interactions/#confirm) interaction to note that the default value is `False` (which is, I think, helpful to know).
> Making note of default for Confirm interactions

- .github/actions/publish-docs-with-mike/action.yml
- .github/actions/publish-docs-with-mike/update_docs_for_version.sh
#119 Gave us the functionality to mark the Github release as a per-release based on the version being bumped. However, documentation publishing would always mark the new version as being the latest release. This change will allow "latest" to point to `X.Y.Z` when `X.Y.Z+1.alpha` is published.
Example of the code working:
* [Pipeline that publishes the docs](https://github.com/plannigan/actions-playground/runs/3636073890?check_suite_focus=true)
* [latest docs page](https://plannigan.github.io/actions-playground/latest/) Note that it does not point to `0.12.0.alpha`. (It points to `0.12.0.dev` because I hadn't copied over the code to publish as a per-release when I first tested the changes.)
Closes #121
> Publish docs base on pre-release status

- pyproject.toml
> Clean up tool configurations

- .github/actions/install-dependencies/action.sh
- .github/actions/install-dependencies/action.yml
- .github/workflows/main.yml
- docker/devbox.dockerfile
- requirements-docs.txt
- requirements-test.txt
This works around a version incompatibility because flake8 requires and older version of `importlib-metadata` (PyCQA/flake8#1438).
> Allow docs dependencies to be installed separately

- CHANGELOG.md
- CONTRIBUTING.md
- columbo/__init__.py
- columbo/_interaction.py
- docs/examples/branching_story.py
- docs/examples/optional_questions.py
- docs/examples/optional_questions_with_value_if_not_asked.py
- docs/index.md
- docs/usage-guide/interactions.md
- docs/usage-guide/optional-questions-and-branching.md
- tests/interaction_test.py
- tests/sample_data.py
* Create an abstract class from which `Echo` and `Acknowledge` inherit
* Add `should_ask` optional parameters
* Only display a message if `should_ask` is `None` or `True`
Closes #356
> feat: `ShouldAsk` for `Echo` and `Acknowledge`

- CHANGELOG.md
- columbo/_cli.py
- columbo/_interaction.py
- docs/usage-guide/interactions.md
- docs/usage-guide/validators.md
- tests/interaction_test.py
Starts enforcing a previous implied expectation.
The check can't be done when creating the `BasicQuestion` because both the default and the validator may depend on the previous answers, which won't be known until runtime.
Closes #357
> Reject default values that do no satisfy the validator

- .github/workflows/publish_release.yml
#305 made the docs dependencies installed separately, but the release workflow was not updated.
> Update workflow for docs dependencies being a different parameter

- CHANGELOG.md
Fake version bump PR to re-trigger the pipeline automation. Actual version bump in in #365.
> Bump version: 0.11.0 → 0.12.0

- CHANGELOG.md
- columbo/_cli.py
- columbo/_interaction.py
There are things that can be done to clean some of this up more to minimize the likelihood of runtime exceptions (can't remove them because of dynamic values). But this explicitly documents all exceptions directly raised by `columbo` and goes up the call chain to the public API. Some of the public API functions have multiple ways the exception could be triggered so the documentation was made more general instead of trying to list every reason.
Fixes #362
> Improve execption documentation

- CHANGELOG.md
- README.md
- columbo/__init__.py
- columbo/_interaction.py
- columbo/_types.py
- columbo/_user_io.py
- docs/api.md
- docs/examples/index_user_prompts.py
- docs/index.md
- docs/usage-guide/interactions.md
- tests/cli_test.py
- tests/interaction_test.py
- tests/sample_data.py
- tests/user_io_test.py
This PR updates the definition of `OptionList` to be _either_ `List[str]` (as is the currently the case) _or_ `Mapping[str, str]`. If a mapping is provided to `Choice` for `options`, the values of the mapping are used as display values when prompting the user. This enhancement allows developers to provide a friendlier user experience while still storing the same answer values as if only a list was provided (current behaviour).
```python
answers = columbo.get_answers(
[
columbo.Choice(
"fav_colour",
message="What is your favourite colour?",
options={
"#FF0000": "Red",
"#00FF00": "Green",
"#0000FF": "Blue",
"#000000": "Black",
},
default="#0000FF",
)
]
)
print(answers)
```
Which gives you:
```
What is your favourite colour?
1 - Red
2 - Green
3 - Blue
4 - Black
Enter the number of your …
```
> feat: Allow `Choice`'s `OptionList` to be a mapping of values → pretty labels

- .github/workflows/publish_release.yml
- CHANGELOG.md
Split building and publishing into distinct jobs to limit access to id-token write permission.
> Switch to using OpenID Connect for publishing artifacts

- .bandit
- docker/validate_docs.sh
- docs/examples/alternate_branching_story.py
- docs/examples/alternate_dynamic_options.py
- docs/examples/alternate_optional_questions.py
- docs/usage-guide/advanced-usage.md
- docs/usage-guide/fundamentals.md
- docs/usage-guide/optional-questions-and-branching.md
- mkdocs.yml
> Add documentation for alternate ways to structure interactions

- CHANGELOG.md
- columbo/_interaction.py
- tests/interaction_test.py
> Validate the type of dynamic values

- CHANGELOG.md
- columbo/_interaction.py
- tests/interaction_test.py
- tests/sample_data.py
Adds validation for each questions type. For `BasicQuestion` and `Choice` this validation has to happen in `get_answers()` since the validator depends on the current `Answers`.
Fixes #374
> Validate value_if_not_asked to prevent invalid values

- CHANGELOG.md
- tests/cli_test.py
#123 removed the functionality, but the test case was not updated to remove the check to see if the deprecation warning was raised. Due to issue fixed in `pytest` 8.0 (pytest-dev/pytest#9036), the warning check would be a no-op because an exception was raised.
This PR removes the check that should no longer exist and updates the changelog to more clearly mark the removal of functionality.
> Remove deprecated check

- .github/workflows/main.yml
- docs/development-guide.md
GitHub is rolling out runners that no longer have `docker-compose`.
> Use docker compose instead of docker-compose
