docs/getting-started.md, docs/index.md, docs/usage-guide.md, mkdocs.yml
=> Add getting started & usage guide

docs/usage-guide/fundamentals.md, docs/usage-guide/interactions.md, docs/usage-guide/validators.md, mkdocs.yml
Also:
Fix issues with cross linking pages
=> Add validator documentation

README.md, docs/development-guide.md, docs/index.md, mkdocs.yml, setup.py
* Move development guide into the docs
* Tell PyPi that the package's long description is markdown
* Add PyPi badges
=> Provide a better intro to the project in the README/long package description

.bumpversion.cfg, docker/bump_version.sh
Also:
* Switch back to original branch after committing
* Correct final message of script
=> Add support for pre-release versions

.bumpversion.cfg, docker-compose.yaml, docker/bump_version.sh, docker/update_docs_for_version.sh, docs/css/version-select.css, docs/index.md, docs/js/version-select.js, mkdocs.yml, requirements-test.txt
Adds the building blocks that can be used to start publishing versioned documentation. Integrating the update script into the CI pipeline will be done in a following PR.
Part of #38
=> Add versioned docs capabilities

requirements-test.txt, util/mkdocs-redirects/mkdocs_redirects/plugin.py, util/mkdocs-redirects/setup.py
Have the content of datarobot/mkdocs-redirects#19 locally while waiting for contribution to be accepted.
=> Use custom mkdocs-redirects implementation for relative redirect urls

README.md, docs/index.md
=> Add CLI example to docs landing page and README

docs/getting-started.md
* Use correct function for CLI example
* Correct CLI argument spelling
* Link to landing page instead of root of domain.
* Tweak section names
=> Fixes for getting started page

.github/workflows/main.yml, docker/devbox.dockerfile, setup.cfg
This PR addresses #42 . Let me know if there are any tweaks that need to be made.
Thanks!
=> Adding Python 3.9 support

setup.cfg
=> Capturing the license as a classifier

docs/api.md, docs/development-guide.md, docs/getting-started.md, docs/usage-guide/command-line.md, docs/usage-guide/fundamentals.md, docs/usage-guide/optional-questions-and-branching.md, docs/usage-guide/validators.md
=> Updated examples and some typos in docs

.github/workflows/publish_release.yml
=> Installing test requirements when updating docs versions

.github/workflows/main.yml, CHANGELOG.md, requirements.txt, setup.cfg
Closes https://github.com/wayfair-incubator/columbo/issues/105
=> Add Dataclass Dependency for Python < 3.7

.github/workflows/detect_version_bump.yml
=> Capturing whether or not a release is a prerelease

CHANGELOG.md, columbo/_interaction.py, docs/examples/optional_questions_with_value_if_not_asked.py, docs/usage-guide/interactions.md, docs/usage-guide/optional-questions-and-branching.md, docs/why-columbo.md, tests/interaction_test.py
=> Adding value_if_not_asked kwarg

docs/development-guide.md
=> Write documentation for the CI pipeline

docs/development-guide.md
=> Update documentation for building the library

docs/api.md, util/mkdocstrings_patch_type_aliases/mkdocstrings_patch_type_aliases/_plugin.py
Also corrected definition of Validator
Fixes #205
=> Update type aplias patching for docs

requirements-docs.txt
Closes #303 
Closes #301
Closes #300
=> Update docs dependencies

CHANGELOG.md, requirements.txt, setup.cfg
=> Update typing-extensions version

.github/workflows/main.yml
=> Install runtime dependencies when running mypy in CI

README.md
Noting Wayfair's funding of the initial development of this project
=> Adding a credits section to the readme

.github/workflows/main.yml, CHANGELOG.md, LICENSE, MAINTAINERS.md, README.md, SECURITY.md, columbo/__init__.py, docker-compose.yaml, docs/development-guide.md, docs/examples/README.md, docs/index.md, docs/why-columbo.md, mkdocs.yml, setup.cfg
* Small tweaks to Why Columbo docs page
* Utilize GitHUb vulnerability reporting
=> Update ownership metadata

mkdocs.yml
Closes mkdocstrings/mkdocstrings#605
=> Update mkdocstrings config to use supported form

docker-compose.yaml
Multiple merge keys were previously supported, but not anymore.
=> Use YAML merge list definition

.bandit, .flake8, .github/actions/verify-wheel/test_module_import.py, .github/workflows/main.yml, docker/run_tests.sh, pyproject.toml
=> Use configuration files for lint tooling paths

CHANGELOG.md, columbo/_interaction.py, tests/interaction_test.py, tests/sample_data.py
=> Add no_user_input support to Displayable

docker-compose.yaml, docs/development-guide.md, pyproject.toml
* usage of hatch
* dependency specification
* publishing
=> Update development guide

.github/actions/initialize-hatch/action.yml, .github/actions/publish-docs-with-mike/action.sh, .github/workflows/main.yml, .github/workflows/publish_release.yml
Action:
* support environment activation
* pass inputs in via environment variables instead of command templating
=> CI hatch improvements

.github/actions/build-dist/action.sh, .github/actions/verify-wheel/action.sh, renovate.json
* pin CI package versions
* tell renovate about pinned versions
* quote shell variables
* build released package from sdist
=> Multiple CI improvements

pyproject.toml
=> Update mkdocs & mkdocs-material versions
